name: Spring Boot CI

on:
  push:
    branches:
      - main  # Kích hoạt workflow khi có sự kiện push vào nhánh 'main'

jobs:
  build:
    runs-on: windows-latest  # Sử dụng môi trường Windows để chạy CI

    steps:
      - name: Checkout the code
        uses: actions/checkout@v2  # Checkout mã nguồn từ GitHub

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'  # Cài đặt JDK 17
          distribution: 'zulu'

      - name: Set up environment variables
        run: |
          echo "DB_URL=${{ secrets.DB_URL }}" >> $env:GITHUB_ENV
          echo "DB_USER=${{ secrets.DB_USER }}" >> $env:GITHUB_ENV
          echo "DB_PASSWORD=${{ secrets.DB_PASSWORD }}" >> $env:GITHUB_ENV

      - name: Build and test the application
        run: |
          cd my-spring-boot-project  # Di chuyển vào thư mục dự án Spring Boot
          .\mvnw.cmd clean test  # Sử dụng mvnw.cmd (dành cho Windows) để build và test ứng dụng
