name: Spring Boot CI

on:
  push:
    branches:
      - main  # Kích hoạt workflow khi có sự kiện push vào nhánh 'main'

jobs:
  build:
    runs-on: windows-latest  # Sử dụng môi trường Windows để chạy CI

    steps:
      - name: Checkout the code
        uses: actions/checkout@v2  # Checkout mã nguồn từ GitHub

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'  # Cài đặt JDK 17
          distribution: 'zulu'  # Sử dụng Oracle JDK hoặc Zulu

      - name: Set up environment variables
        run: |
          echo "DB_URL=${{ secrets.DB_URL }}" >> $env:GITHUB_ENV
          echo "DB_USER=${{ secrets.DB_USER }}" >> $env:GITHUB_ENV
          echo "DB_PASSWORD=${{ secrets.DB_PASSWORD }}" >> $env:GITHUB_ENV

      - name: Build and test the application
        run: |
          # Di chuyển vào thư mục chứa tệp pom.xml của dự án
          cd source\backend\QuizExam_Student  # Đảm bảo đường dẫn chính xác đến thư mục chứa pom.xml

          # Kiểm tra xem tệp pom.xml có tồn tại trong thư mục không
          dir  # Lệnh này sẽ liệt kê các tệp trong thư mục để bạn có thể kiểm tra có tệp pom.xml hay không

          # Kiểm tra tệp mvnw.cmd có tồn tại không
          dir mvnw.cmd  # Kiểm tra tệp mvnw.cmd có trong thư mục không

          # Chạy Maven Wrapper cho Windows (mvnw.cmd)
          .\mvnw.cmd clean test -X  # Sử dụng mvnw.cmd cho Windows và bật chế độ debug
