name: Spring Boot CI

on:
  push:
    branches:
      - main  # Kích hoạt workflow khi có sự kiện push vào nhánh 'main'

jobs:
  build:
    runs-on: windows-latest  # Sử dụng môi trường Windows để chạy CI

    steps:
      - name: Checkout the code
        uses: actions/checkout@v2  # Checkout mã nguồn từ GitHub

      - name: Set up Oracle JDK 17
        run: |
          # Tải Oracle JDK 17
          Invoke-WebRequest -Uri "https://download.oracle.com/java/17/latest/jdk-17_windows-x64_bin.exe" -OutFile "jdk-17_windows-x64_bin.exe"
          Start-Process "jdk-17_windows-x64_bin.exe" -ArgumentList "/s", "/v/qn" -Wait
          # Thiết lập JDK 17 như môi trường mặc định
          $env:JAVA_HOME="C:\Program Files\Java\jdk-17"
          echo "JAVA_HOME=$env:JAVA_HOME" >> $env:GITHUB_ENV
          echo "PATH=$env:JAVA_HOME\bin;$env:PATH" >> $env:GITHUB_ENV

      - name: Set up environment variables
        run: |
          echo "DB_URL=${{ secrets.DB_URL }}" >> $env:GITHUB_ENV
          echo "DB_USER=${{ secrets.DB_USER }}" >> $env:GITHUB_ENV
          echo "DB_PASSWORD=${{ secrets.DB_PASSWORD }}" >> $env:GITHUB_ENV

      - name: Build and test the application
        run: |
          cd source\backend\QuizExam_Student  # Di chuyển vào thư mục dự án Spring Boot
          .\mvnw.cmd clean test  # Sử dụng mvnw.cmd (dành cho Windows) để build và test ứng dụng
