name: Spring Boot CI

on:
  push:
    branches:
      - main  # Kích hoạt workflow khi có sự kiện push vào nhánh 'main'

jobs:
  build:
    runs-on: windows-latest  # Sử dụng môi trường Windows để chạy CI

    steps:
      - name: Checkout the code
        uses: actions/checkout@v2  # Checkout mã nguồn từ GitHub

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'  # Cài đặt JDK 17
          distribution: 'zulu'  # Có thể thay thế 'zulu' bằng 'oraclejdk' nếu bạn muốn sử dụng Oracle JDK

      - name: Set up environment variables
        run: |
          echo "DB_URL=${{ secrets.DB_URL }}" >> $env:GITHUB_ENV
          echo "DB_USER=${{ secrets.DB_USER }}" >> $env:GITHUB_ENV
          echo "DB_PASSWORD=${{ secrets.DB_PASSWORD }}" >> $env:GITHUB_ENV

      - name: Build and test the application
        run: |
          # Di chuyển đến thư mục chứa dự án Spring Boot
          cd source\backend\QuizExam_Student  # Đảm bảo đường dẫn chính xác

          # Chạy Maven Wrapper (mvnw.cmd) để build và test ứng dụng
          .\mvnw.cmd clean test  # Đảm bảo dùng mvnw.cmd cho Windows
